language: php

sudo: false

php:
  - "5.5"
  - "5.6"
  - "7"
  - "hhvm"

matrix:
  include:
    - php: "5.5"
      env: CHECKSTYLE="YES" COVERAGE="YES"
  allow_failures:
    - php: "7"
    - php: "hhvm"

install: composer install

script: ./vendor/bin/ci-runner
